baseURL = "https://nritsche.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Rick Nitsche"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "I'm Rick Nitsche"
author = "Rick Nitsche"
description = "Call me Rick"
profilePicture = "images/profile.jpeg"
keywords = ""
favicon = "favicons/"
customCss = []

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/rick-nitsche-a552bb14a/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/nritsche"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/instergrammophon/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:nitsche.rick+web@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

